# Generated by Django 3.1.7 on 2021-03-10 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='eptfProjeto',
            fields=[
                ('idProjeto', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('cdProjeto', models.CharField(max_length=20)),
                ('nmProjeto', models.CharField(max_length=80)),
                ('deProjeto', models.CharField(blank=True, max_length=200, null=True)),
                ('deCadastro', models.DateTimeField()),
                ('dtAprovacao', models.DateField(blank=True, null=True)),
                ('dtCancelamento', models.DateField(blank=True, null=True)),
                ('flStatus', models.IntegerField(choices=[(1, 'Novo'), (2, 'Aprovado'), (3, 'Cancelado')])),
                ('nmUsuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='egstGerenciamento',
            fields=[
                ('idGerenciamento', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('vlOrcamento', models.DecimalField(decimal_places=2, max_digits=9)),
                ('vlGasto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('nuProjeto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.eptfprojeto')),
            ],
        ),
    ]
